"""Abstract base class for trading strategies."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Any

import pandas as pd

from cryptrink.exchange.base import OrderSide


class SignalType(str, Enum):
    """Type of trading signal."""

    ENTRY_LONG = "entry_long"
    ENTRY_SHORT = "entry_short"
    EXIT_LONG = "exit_long"
    EXIT_SHORT = "exit_short"
    HOLD = "hold"


class SignalStrength(str, Enum):
    """Strength/confidence of the signal."""

    WEAK = "weak"
    MODERATE = "moderate"
    STRONG = "strong"


@dataclass(frozen=True)
class Signal:
    """Trading signal generated by a strategy."""

    signal_type: SignalType
    symbol: str
    strength: SignalStrength
    timestamp: datetime
    price: Decimal
    suggested_quantity: Decimal | None = None
    stop_loss: Decimal | None = None
    take_profit: Decimal | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def side(self) -> OrderSide | None:
        """Get order side for this signal."""
        if self.signal_type in (SignalType.ENTRY_LONG, SignalType.EXIT_SHORT):
            return OrderSide.BUY
        if self.signal_type in (SignalType.ENTRY_SHORT, SignalType.EXIT_LONG):
            return OrderSide.SELL
        return None

    @property
    def is_entry(self) -> bool:
        """Check if this is an entry signal."""
        return self.signal_type in (SignalType.ENTRY_LONG, SignalType.ENTRY_SHORT)

    @property
    def is_exit(self) -> bool:
        """Check if this is an exit signal."""
        return self.signal_type in (SignalType.EXIT_LONG, SignalType.EXIT_SHORT)


@dataclass
class StrategyContext:
    """Context provided to strategy for decision making."""

    symbol: str
    current_price: Decimal
    timestamp: datetime

    # OHLCV data
    ohlcv: pd.DataFrame  # columns: open, high, low, close, volume

    # Current position (if any)
    position_size: Decimal = Decimal("0")
    position_side: OrderSide | None = None
    position_entry_price: Decimal | None = None

    # Account info
    available_balance: Decimal = Decimal("0")
    total_equity: Decimal = Decimal("0")

    # Additional data
    orderbook_bid: Decimal | None = None
    orderbook_ask: Decimal | None = None
    recent_trades: list[Any] = field(default_factory=list)

    @property
    def has_position(self) -> bool:
        """Check if there's an open position."""
        return self.position_size != Decimal("0")

    @property
    def is_long(self) -> bool:
        """Check if current position is long."""
        return self.position_side == OrderSide.BUY and self.has_position

    @property
    def is_short(self) -> bool:
        """Check if current position is short."""
        return self.position_side == OrderSide.SELL and self.has_position


class BaseStrategy(ABC):
    """Abstract base class for trading strategies.

    All trading strategies must implement this interface. Strategies
    analyze market data and generate trading signals.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Unique strategy name/identifier."""
        ...

    @property
    @abstractmethod
    def description(self) -> str:
        """Human-readable strategy description."""
        ...

    @property
    def required_history(self) -> int:
        """Number of historical candles required.

        Override to specify how many candles the strategy needs
        to generate signals. Default is 100.
        """
        return 100

    @property
    def timeframe(self) -> str:
        """Preferred timeframe for the strategy.

        Override to specify preferred candle timeframe.
        Default is "1h" (1 hour).
        """
        return "1h"

    @abstractmethod
    def generate_signal(self, context: StrategyContext) -> Signal:
        """Generate a trading signal based on current market state.

        Args:
            context: Current market context with price data and position info.

        Returns:
            Trading signal (may be HOLD if no action needed).
        """
        ...

    def validate_context(self, context: StrategyContext) -> bool:
        """Validate that context has sufficient data.

        Args:
            context: Strategy context to validate.

        Returns:
            True if context is valid for this strategy.
        """
        if context.ohlcv is None or context.ohlcv.empty:
            return False
        if len(context.ohlcv) < self.required_history:
            return False
        return True

    def calculate_position_size(
        self,
        context: StrategyContext,
        signal: Signal,
        risk_per_trade: Decimal = Decimal("0.02"),
    ) -> Decimal:
        """Calculate suggested position size based on risk.

        Default implementation uses fixed fractional position sizing.
        Override for custom position sizing logic.

        Args:
            context: Current market context.
            signal: Generated signal.
            risk_per_trade: Maximum risk per trade as decimal (0.02 = 2%).

        Returns:
            Suggested position size in base currency.
        """
        if signal.stop_loss is None:
            # No stop loss, use simple percentage of equity
            return context.total_equity * risk_per_trade / context.current_price

        # Risk-based position sizing
        risk_amount = context.total_equity * risk_per_trade
        price_risk = abs(context.current_price - signal.stop_loss)

        if price_risk == 0:
            return Decimal("0")

        return risk_amount / price_risk

    def on_trade_executed(
        self,
        symbol: str,
        side: OrderSide,
        quantity: Decimal,
        price: Decimal,
        timestamp: datetime,
    ) -> None:
        """Called when a trade is executed.

        Override to track trades or update internal state.

        Args:
            symbol: Traded symbol.
            side: Trade side.
            quantity: Trade quantity.
            price: Execution price.
            timestamp: Execution timestamp.
        """
        pass

    def reset(self) -> None:
        """Reset strategy state.

        Override to reset any internal state when starting fresh
        or between backtesting runs.
        """
        pass
