#!/usr/bin/env python3
"""Helper script to set up secrets and configuration for local development.

This script automates the complete setup process:
1. Creates the secrets directory with proper permissions
2. Moves PEM files from project root to secrets/
3. Generates base64-encoded private key for CI/CD
4. Creates .env.local with all required configuration
5. Validates the setup
"""

import base64
import contextlib
import sys
from pathlib import Path


def create_secrets_dir() -> Path:
    """Create secrets directory with secure permissions."""
    secrets_dir = Path("secrets")
    secrets_dir.mkdir(exist_ok=True)

    # Set restrictive permissions on Unix-like systems
    # Windows will ignore this gracefully
    with contextlib.suppress(Exception):
        secrets_dir.chmod(0o700)

    return secrets_dir


def convert_pem_to_base64(pem_path: Path) -> str:
    """Convert PEM file to base64-encoded raw Ed25519 seed.

    Args:
        pem_path: Path to the PEM file containing Ed25519 private key.

    Returns:
        Base64-encoded string of the raw 32-byte Ed25519 seed.
    """
    from cryptography.hazmat.backends import default_backend
    from cryptography.hazmat.primitives import serialization

    pem_data = pem_path.read_bytes()
    private_key_obj = serialization.load_pem_private_key(
        pem_data,
        password=None,
        backend=default_backend(),
    )

    # Extract raw 32-byte seed from PKCS#8 format
    raw_private = private_key_obj.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )

    return base64.b64encode(raw_private).decode("ascii")


def generate_env_local_content() -> str:
    """Generate complete .env.local file content with all configuration options.

    Returns:
        Complete .env.local file content as string.
    """
    return """# Cryptrink Local Environment Configuration
# This file is gitignored - safe to store secrets here
# Generated by scripts/setup_secrets.py

# =============================================================================
# Revolut X API Configuration
# =============================================================================

# Your Revolut X API Key (64-character alphanumeric string)
# Get this from: https://revx.revolut.com/ → Profile → API Keys
REVOLUTX_API_KEY=your_api_key_here

# Path to your Ed25519 private key file
# The setup script automatically moves your private.pem here
REVOLUTX_PRIVATE_KEY_PATH=./secrets/private.pem

# Revolut X API Base URL (includes /api/1.0 prefix)
# Note: Revolut X does not have a separate sandbox environment
REVOLUTX_BASE_URL=https://revx.revolut.com/api/1.0

# =============================================================================
# General Application Settings
# =============================================================================

# Execution mode: 'paper' (simulated) or 'live' (real trades)
# IMPORTANT: Keep as 'paper' for testing!
CRYPTRINK_EXECUTION_MODE=paper

# Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
# Use DEBUG for troubleshooting, INFO for normal operation
CRYPTRINK_LOG_LEVEL=INFO

# =============================================================================
# Risk Management
# =============================================================================

# Maximum position size as percentage of portfolio (0.0-1.0)
# Example: 0.1 = max 10% of portfolio in a single position
RISK_MAX_POSITION_SIZE_PCT=0.1

# Maximum daily loss as percentage of portfolio (0.0-1.0)
# Example: 0.05 = stop trading if daily loss exceeds 5%
RISK_MAX_DAILY_LOSS_PCT=0.05

# Maximum drawdown as percentage of peak equity (0.0-1.0)
# Example: 0.15 = stop trading if drawdown exceeds 15%
RISK_MAX_DRAWDOWN_PCT=0.15

# =============================================================================
# Database Configuration
# =============================================================================

# Database URL for storing trades, positions, and analytics
# Default uses SQLite with async support
DB_URL=sqlite+aiosqlite:///cryptrink.db

# Alternative PostgreSQL configuration (uncomment to use):
# DB_URL=postgresql+asyncpg://user:password@localhost:5432/cryptrink

# =============================================================================
# Notifications (Optional)
# =============================================================================

# Enable/disable Discord notifications
NOTIFY_DISCORD_ENABLED=false

# Discord webhook URL (only needed if NOTIFY_DISCORD_ENABLED=true)
# Get webhook from: Discord Server → Edit Channel → Integrations → Webhooks
NOTIFY_DISCORD_WEBHOOK_URL=

# =============================================================================
# Advanced Settings (Optional)
# =============================================================================

# Enable test mode (runs tests without affecting production state)
# TEST_MODE=false

# Custom exchange rate limits (requests per second)
# EXCHANGE_RATE_LIMIT_RPS=10

# WebSocket reconnection settings
# WS_RECONNECT_DELAY_SECONDS=5
# WS_MAX_RECONNECT_ATTEMPTS=10
"""


def create_env_local_file(path: Path) -> None:
    """Create .env.local file with complete configuration.

    Args:
        path: Path where to create the .env.local file.
    """
    content = generate_env_local_content()
    path.write_text(content, encoding="utf-8")


def validate_setup(secrets_dir: Path, env_local: Path) -> list[str]:
    """Validate the setup and return list of warnings/issues.

    Args:
        secrets_dir: Path to secrets directory.
        env_local: Path to .env.local file.

    Returns:
        List of warning/issue messages (empty if all good).
    """
    issues = []

    # Check secrets directory
    if not secrets_dir.exists():
        issues.append("secrets/ directory not found")

    # Check private key file
    private_pem = secrets_dir / "private.pem"
    if not private_pem.exists():
        issues.append("secrets/private.pem not found")

    # Check .env.local file
    if not env_local.exists():
        issues.append(".env.local not found")
    else:
        content = env_local.read_text()
        if "your_api_key_here" in content:
            issues.append(".env.local still contains placeholder API key")

    return issues


def main() -> None:
    """Main setup function."""
    print("🔐 Cryptrink Setup Script")
    print("=" * 70)
    print()
    print("This script will:")
    print("  1. Create the secrets/ directory")
    print("  2. Move your PEM files to secrets/")
    print("  3. Generate base64-encoded key for GitHub Actions")
    print("  4. Create .env.local with all configuration options")
    print()

    # Check for PEM files in current directory
    private_pem = Path("private.pem")
    public_pem = Path("public.pem")

    if not private_pem.exists():
        print("❌ Error: private.pem not found in project root")
        print()
        print("Please generate your Ed25519 key pair first:")
        print()
        print("  # Generate private key")
        print("  openssl genpkey -algorithm ed25519 -out private.pem")
        print()
        print("  # Generate public key")
        print("  openssl pkey -in private.pem -pubout -out public.pem")
        print()
        print("Then run this script again.")
        sys.exit(1)

    if not public_pem.exists():
        print("⚠️  Warning: public.pem not found")
        print("   This is optional but recommended for reference.")
        print()

    # Step 1: Create secrets directory
    print("Step 1: Creating secrets directory...")
    secrets_dir = create_secrets_dir()
    print(f"  ✓ Created: {secrets_dir.absolute()}")
    print()

    # Step 2: Move PEM files
    print("Step 2: Moving PEM files to secrets/...")
    target_private = secrets_dir / "private.pem"
    target_public = secrets_dir / "public.pem"

    # Handle case where files might already be in secrets/
    if target_private.exists():
        print("  [INFO] secrets/private.pem already exists")
        if private_pem.exists():
            print("  [WARN] Both private.pem and secrets/private.pem exist")
            response = input("  Overwrite secrets/private.pem? (y/N): ").strip().lower()
            if response == "y":
                private_pem.replace(target_private)
                print("  ✓ Replaced: secrets/private.pem")
    else:
        private_pem.rename(target_private)
        print("  ✓ Moved: private.pem → secrets/private.pem")

    if public_pem.exists():
        if target_public.exists():
            print("  [INFO] secrets/public.pem already exists, skipping")
        else:
            public_pem.rename(target_public)
            print("  ✓ Moved: public.pem → secrets/public.pem")

    # Set file permissions
    try:
        target_private.chmod(0o600)
        if target_public.exists():
            target_public.chmod(0o600)
        print("  ✓ Set secure file permissions (600)")
    except Exception:
        print("  ⚠️  Could not set file permissions (Windows or restricted access)")

    print()

    # Step 3: Convert to base64 for CI
    print("Step 3: Converting private key to base64 for CI/CD...")
    try:
        base64_key = convert_pem_to_base64(target_private)
        print(f"  ✓ Converted: {len(base64_key)} characters (raw 32-byte seed)")
        ci_key = base64_key
    except Exception as e:
        print(f"  ❌ Error converting key: {e}")
        print("  ⚠️  Install cryptography: poetry install")
        ci_key = None

    print()

    # Step 4: Create .env.local
    env_local = Path(".env.local")
    if env_local.exists():
        print("Step 4: .env.local already exists")
        response = input("  Overwrite .env.local? (y/N): ").strip().lower()
        if response == "y":
            create_env_local_file(env_local)
            print(f"  ✓ Created: {env_local}")
            print("  [WARN] Remember to add your REVOLUTX_API_KEY!")
        else:
            print("  [INFO] Keeping existing .env.local")
    else:
        print("Step 4: Creating .env.local with full configuration...")
        create_env_local_file(env_local)
        print(f"  ✓ Created: {env_local}")
        print("  ⚠️  Remember to add your REVOLUTX_API_KEY!")

    print()

    # Validation
    print("Step 5: Validating setup...")
    issues = validate_setup(secrets_dir, env_local)
    if not issues:
        print("  ✓ Setup validation passed!")
    else:
        print("  ⚠️  Issues found:")
        for issue in issues:
            print(f"     - {issue}")

    print()
    print("=" * 70)
    print("✅ Setup Complete!")
    print("=" * 70)
    print()

    # Next steps
    print("📝 Next Steps:")
    print()
    print("1. Add your Revolut X API Key to .env.local:")
    print(f"   Edit: {env_local.absolute()}")
    print("   Replace: REVOLUTX_API_KEY=your_api_key_here")
    print("   With your actual 64-character API key from Revolut X")
    print()

    print("2. Verify your configuration:")
    print('   poetry run python -c "from cryptrink.core.config import Settings; ')
    print("   s = Settings(); print(f'✓ Config loaded')\"")
    print()

    print("3. Run integration tests:")
    print("   poetry run pytest tests/integration/ -v -m integration")
    print()

    if ci_key:
        print("4. For GitHub Actions, add these secrets to your repository:")
        print("   Go to: Settings → Secrets and variables → Actions → New secret")
        print()
        print("   REVOLUTX_API_KEY: <paste_your_api_key>")
        print(f"   REVOLUTX_PRIVATE_KEY: {ci_key}")
        print("   REVOLUTX_BASE_URL: https://revx.revolut.com/api/1.0")
        print()

    # Security reminders
    print("🔒 Security Reminders:")
    print("   ✓ Never commit .env.local or *.pem files")
    print("   ✓ The secrets/ directory is gitignored")
    print("   ✓ Keep your API keys secure")
    print("   ✓ Use CRYPTRINK_EXECUTION_MODE=paper for testing")
    print("   ✓ Regularly rotate your API keys")
    print()

    print("📚 For more information, see GETTING_STARTED.md")
    print()


if __name__ == "__main__":
    main()
